[action]
move_mouse_step = 10  # pixels per press

[action.key_bindings]
left_click = "Enter"
right_click = "Shift+Enter"
middle_click = "Cmd+Enter"
mouse_down = "Shift+I"
mouse_up = "Shift+U"
move_mouse_up = "Up"
move_mouse_down = "Down"
move_mouse_left = "Left"
move_mouse_right = "Right"
